### ISSUE TITLE
Request support on Django2

### ISSUE THREAD

**Issue by elcolie** [philippbosch/django-geoposition#100]
Hi
Your package is great!
In order to fasten your upgrade process I will post my problem when first contact with Django2
```python
Traceback (most recent call last):
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sarit/.pyenv/versions/3.6.4/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/rest_framework/viewsets.py", line 95, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/rest_framework/mixins.py", line 22, in create
    headers = self.get_success_headers(serializer.data)
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/rest_framework/serializers.py", line 537, in data
    ret = super(Serializer, self).data
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/rest_framework/serializers.py", line 504, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/lib/python3.6/site-packages/rest_framework/fields.py", line 1858, in to_representation
    return self.model_field.value_to_string(obj)
  File "/Users/sarit/.pyenv/versions/3.6.4/envs/poink/src/django-geoposition/geoposition/fields.py", line 50, in value_to_string
    value = self._get_val_from_obj(obj)
AttributeError: 'GeopositionField' object has no attribute '_get_val_from_obj'
```

**Comment by liginv** [comment]
Is there any development ongoing for the django2 support?

**Comment by elcolie** [comment]
@liginv 
For Django2 check out my `master` branch.

https://github.com/elcolie/django-geoposition
I made change on single line and the package is back to live again

```python setup.py sdist```
And `pip install django-geoposition-0.3.1.tar.gz`
I had test it in my hobby repository here. It works.


If you are in the hurry get this file
[django-geoposition-0.3.1.tar.gz](https://github.com/philippbosch/django-geoposition/files/1800248/django-geoposition-0.3.1.tar.gz)

**Comment by liginv** [comment]
It works. Thank you.

**Comment by elcolie** [comment]
For new comer. In order to work with `pip-tools` easier. Use this line
Place this line to `requirements.in`
`-e git+git@github.com:elcolie/django-geoposition.git@v0.3.2#egg=django-geoposition`

Then `pip-compile requirements.in`
And finally `pip install -r requirements.txt`

**Comment by NgariC** [comment]
I have tried the command pip install django-geoposition-0.3.1.tar.gz only to get the error "FileNotFoundError: [Errno 2]"

**Comment by elcolie** [comment]
@NgariC If you install from file you have to download it first!

**Comment by NgariC** [comment]
i downloaded the file but i dont know how to install from it.
how do install from the file, what command do i use?

**Comment by liginv** [comment]
@NgariC hope you downloaded this one https://github.com/elcolie/django-geoposition.

- then `cd` into the folder
- run the following command from inside the folder
`python setup.py sdist`

Now the new django-geoposition that support django2.0 is built. but not installed in your environment; now assuming you are using a virtual environment now type,
`pip install django-geoposition-0.3.1.tar.gz`

this will install the new django-geoposition that support django2.x.x.

Hope this helps.
